Updated contribution.
rhysd/dot-github pull request #4
Opened 2020-05-20 12:28 UTC by TheAwesome98-Real

### What was a problem?

The English was not so good.

### How this PR fixes the problem?

It makes the English grammar better.

### Check lists (check `x` in `[ ]` of list items)

- [x] Test passed
- [x] Coding style (indentation, etc)

### Additional Comments (if any)

We can also make a Japanese version, if you want.

2020-05-20 14:38 UTC, GeorgeWL requested changes

2020-05-20 14:38 UTC, GeorgeWL commented on example/CONTRIBUTING.md
> +You can speak in Japanese or English.  Japanese is better but English is also OK.
this isn't better grammar either though.

If you look the rest is written in third-person active, this new sentence is first-person neutral.

2020-05-20 14:38 UTC, GeorgeWL commented on example/CONTRIBUTING.md
> +You can speak in Japanese or English.  Japanese is better but English is also OK.
My suggestion, rewrite the entire sentence to something like:

Please use either Japanese or English, Japanese is the preferred language.

2020-05-21 03:46 UTC, rhysd approved these changes
Thanks!

2020-05-21 03:47 UTC, merged